# plugins:
#   - jekyll-analytics
# Analytics
analytics:
  provider               :  "google-universal" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-141790565-1"

collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  syllabi:
    output: true
    # permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: "teaching"
    values:
      layout: "class"
  - scope:
      path: ""
      type: "syllabi"
    values:
      layout: "class"
  - scope:
      path: ""
      type: "publications"
    values:
      layout: "publication"
  - scope:
      path: ""
    values:
      layout: "default"

# Outputting
# permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: America/Los_Angeles # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
